### ISSUE TITLE
Сделать, чтобы при нажатии кнопки Submit что-то происходило

### ISSUE THREAD

**Issue by romka-u** [bminaiev/contest-platform#6]
Либо какое-то сообщение, что "успешно отправлено", либо может быть на страницу submissions редиректить 🤔

**Comment by bminaiev** [comment]
Ага, я думал либо рядом с choose file, либо отдельной колонкой, сделать результат последнего сабмита. Типа после отправки там должно быть что-то типа "Pending", а потом оно автометически раз в секунду должно обновляться.

**Comment by bminaiev** [comment]
Добавил еще одну колонку, которая автоматически обновляется после сабмита. Но возможно надо будет еще race conditions пофиксить.
![image](https://github.com/bminaiev/contest-platform/assets/2011126/6cd07752-d05e-485d-b0a1-601d2c6cf782)
